version: '3.8'

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www/html:delegated
        ports:
            - "8000:9000"
        environment:
            - APP_NAME=${APP_NAME:-Laravel}
            - APP_ENV=${APP_ENV:-local}
            - APP_KEY=${APP_KEY:-base64:3SHnI0Xj+IoPMFjK8iU3ZH3m6RCcflObtG6L6SzNb8o=}
            - APP_DEBUG=${APP_DEBUG:-true}
            - APP_URL=${APP_URL:-http://localhost}
            - APP_LOCALE=${APP_LOCALE:-en}
            - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE:-en}
            - APP_FAKER_LOCALE=${APP_FAKER_LOCALE:-en_US}
            - APP_MAINTENANCE_DRIVER=${APP_MAINTENANCE_DRIVER:-file}
            - PHP_CLI_SERVER_WORKERS=${PHP_CLI_SERVER_WORKERS:-4}
            - BCRYPT_ROUNDS=${BCRYPT_ROUNDS:-12}
            - LOG_CHANNEL=${LOG_CHANNEL:-stack}
            - LOG_STACK=${LOG_STACK:-single}
            - LOG_DEPRECATIONS_CHANNEL=${LOG_DEPRECATIONS_CHANNEL:-null}
            - LOG_LEVEL=${LOG_LEVEL:-debug}
            - DB_CONNECTION=${DB_CONNECTION:-sqlite}
            - SESSION_DRIVER=${SESSION_DRIVER:-database}
            - SESSION_LIFETIME=${SESSION_LIFETIME:-120}
            - SESSION_ENCRYPT=${SESSION_ENCRYPT:-false}
            - SESSION_PATH=${SESSION_PATH:-/}
            - SESSION_DOMAIN=${SESSION_DOMAIN:-null}
            - BROADCAST_CONNECTION=${BROADCAST_CONNECTION:-log}
            - FILESYSTEM_DISK=${FILESYSTEM_DISK:-local}
            - QUEUE_CONNECTION=${QUEUE_CONNECTION:-database}
            - CACHE_STORE=${CACHE_STORE:-database}
            - MEMCACHED_HOST=${MEMCACHED_HOST:-127.0.0.1}
            - REDIS_CLIENT=${REDIS_CLIENT:-phpredis}
            - REDIS_HOST=${REDIS_HOST:-127.0.0.1}
            - REDIS_PASSWORD=${REDIS_PASSWORD:-null}
            - REDIS_PORT=${REDIS_PORT:-6379}
            - MAIL_MAILER=${MAIL_MAILER:-log}
            - MAIL_SCHEME=${MAIL_SCHEME:-null}
            - MAIL_HOST=${MAIL_HOST:-127.0.0.1}
            - MAIL_PORT=${MAIL_PORT:-2525}
            - MAIL_USERNAME=${MAIL_USERNAME:-null}
            - MAIL_PASSWORD=${MAIL_PASSWORD:-null}
            - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-"hello@example.com"}
            - MAIL_FROM_NAME=${MAIL_FROM_NAME:-"Laravel"}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
            - AWS_BUCKET=${AWS_BUCKET:-}
            - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT:-false}
        networks:
            - app-network

    frontend:
        build:
            context: ./
            dockerfile: frontend/Dockerfile
        container_name: vue-frontend
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
